module FiskalyService
  module DSFinVK
    module Exports
      # DSFinVK APIs for {https://developer.fiskaly.com/api/dsfinvk/v1#operation/getExportDownload exports download}
      #
      # DSFinV-K export download
      #
      # This endpoint returns the TAR file generated by the export operation.
      class Download < Base
        attr_reader :export_id

        # @param token [String] JWT token
        # @param export_id [String] Identifies an Export
        # @return [FiskalyService::DSFinVK::Exports::Download] The Retrieved object
        def initialize(token:, export_id:)
          super(token: token)

          @export_id = export_id
        end

        # Retrive a specific export file
        #
        # @return [Hash] Formatted response informations
        def call
          request = self.class.get("/exports/#{export_id}/download", headers: headers)

          handle_request(request)
        end

        private

        def handle_request(request)
          if request.success?
            {
              status: :ok,
              body: request.response.body
            }
          else
            {
              status: :error,
              message: request.response.message,
              body: JSON.parse(request.response.body)
            }
          end
        end
      end
    end
  end
end
